// react/ql-sinh-vien/src/componets/Search.component.js

import Button from "./share/Button.componet";
import { useContext, useState } from "react";
import { SvContext } from "./share/Context";
function Seach() {
    const data = useContext(SvContext)
    const { search, setSearch } = data;
    const handler = function (e) {
        e.preventDefault();
        console.log(search);
    }
    const handlInput = function (e) {
        setSearch(e.target.value)
    }
    return (
        <form id="form-1" action="" onSubmit={handler}>
            <fieldset className="boder-layout">
                <legend>Tìm kiếm</legend>
                <label className="label_form-group" htmlFor="txtTuKhoa">Tìm kiếm sinh viên: </label>
                <input
                    id="txtTuKhoa"
                    placeholder="Từ khóa cần tìm"
                    value={search}
                    className="seach-input"
                    onChange={handlInput}
                />
                <Button
                    type="submit"
                    className='seach btn'
                    text="Tìm kiếm"
                />
            </fieldset>
        </form>
    )
}


export default Seach

// VueJs/vue-qlsv/src/components/Search.vue
<template>
<form id="form-1" @submit.prevent="handleSubmit" >
        <fieldset class="boder-layout">
            <legend>Tìm kiếm</legend>
            <label class="seach__label label-color" for="txtTuKhoa">Từ khóa:  </label>
            <input class="search__input" type="text" id="txtTuKhoa" placeholder="Từ khóa cần tìm" v-model.lazy="tukhoa">
            <button class="seach btn" type="submit">Tìm kiếm</button>
            <label>{{ tukhoa }}</label>
        </fieldset>
    </form>
</template>

<script setup>
import { ref, watch } from "vue"
const props = defineProps({
  listSinhVien:Array
})
const tukhoa=ref('')
const emit = defineEmits(['response'])
function handleSubmit(){
    // console.log(tukhoa.value)
    emit('response', tukhoa.value)
    tukhoa.value='';
}
</script>

<style scoped>
.boder-layout{
    width: 100%;
    display: flex;
}
.search__input{
    flex: 3;
    max-width: 600px;
}
</style>
